### ISSUE TITLE
White labels do not appear

### ISSUE THREAD

**Issue by arnaudtibco** [Donut-Mod-Team/donut-mod#128]
When using version 1.0 in Spotfire 11.4 LTS, the white labels do not show.

![Screen Shot 2021-12-10 at 09 11 35](https://user-images.githubusercontent.com/15086293/145539906-0881e9a0-eaaa-4a1b-9f2f-dad76c5bc389.png)

**Comment by krasen86** [comment]
The bug is resolved in 11.4.1
