### ISSUE TITLE
Labels color switch

### ISSUE THREAD

**Issue by arnaudtibco** [Donut-Mod-Team/donut-mod#43]
Grey labels should switch to white, based on the sector color to make them more readable.

![Screen Shot 2021-10-15 at 12 36 41](https://user-images.githubusercontent.com/15086293/137474481-8d816886-0393-470e-94d9-8d08622c2bdb.png)

**Comment by krasen86** [comment]
Closed in #74

**Comment by krasen86** [comment]
Closed in #74
