### ISSUE TITLE
Displaying labels

### ISSUE THREAD

**Issue by arnaudtibco** [Donut-Mod-Team/donut-mod#46]
It should be possible to show labels as percentage, value or category and/or in combination.
Here I suggest to add a custom setting panel to provide these options to the author. Examples of mods using this:
- Word cloud: https://github.com/jacobsjan/WordCloud2
- Area chart: https://github.com/TIBCOSoftware/spotfire-mods/tree/master/examples/js-areachart-d3

These settings should be available to author only when Spotfire is in Editing mode.

**Comment by chrytsa** [comment]
This was closed as per #74
