### ISSUE TITLE
Semi circle donut chart

### ISSUE THREAD

**Issue by arnaudtibco** [Donut-Mod-Team/donut-mod#49]
Would be nice to be able to change donut chart to a semi circle. Semi Circle Donut Chart is simply a Donut Chart cut in half. The elements are still divided into sectors, illustrating numerical proportion like a basic pie or donut chart.

![DVP_1_100-76](https://user-images.githubusercontent.com/15086293/137476182-9f733a78-0889-4c37-a0b0-104405cd65ef.png)

**Comment by chrytsa** [comment]
Issue closed as per #93
